### ISSUE TITLE
lesson won't load

### ISSUE THREAD

**Issue by kseggelke918** [learn-co-curriculum/programming-univbasics-4-array-simple-array-manipulations#3]
When I open the IDE, I get this message and it isn't loading the lab.  

[learn.co error message.docx](https://github.com/learn-co-curriculum/programming-univbasics-4-array-simple-array-manipulations/files/3331389/learn.co.error.message.docx)

**Comment by maxwellbenton** [comment]
Hi @kseggelke918,

I've taken a look at this lesson and tested it on the IDE, but was unable to replicate your error. However, yesterday there were reported issues with labs being unable to open in the IDE that have since been resolved. I believe this may be what caused this error for you and the lab should load now when opened in the IDE.

I am going to close this issue, but please reopen if you continue to experience this problem.
